# Generated by Django 2.0.3 on 2018-03-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='annual_accrual_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_allowable_accrual_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='remaining_accrual_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
