# Generated by Django 2.0.3 on 2018-03-19 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('start_date', models.DateTimeField(verbose_name='Request Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Request End Date')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vacation Requests',
                'db_table': 'requests',
            },
        ),
    ]
