# Generated by Django 2.0.3 on 2018-03-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='number_of_days',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
